[workspace]
channels = ["conda-forge"]
name = "nbia-toolkit"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
ipython = ">=9.4.0,<10"
ipykernel = ">=6.29.5,<7"
jupyterlab = ">=4.4.4,<5"
click = ">=8.2.1,<9"

[pypi-dependencies]
nbiatoolkit = ">=1.3.1, <2"
